title: Essayer
description: Try again. Fail again. Fail better.
baseurl: /essayer
url: https://constellationcolon.github.io
permalink: none
exclude: [archive, bin]

collections:
  details:
  poems:
    output: true

github: constellationcolon
linkedin: suhang42

markdown: Kramdown

scholar:
  bibliography: "**/*.bib{,tex}"
  bibliography_template: bib
  bibliography_list_tag: div
  bibliography_item_tag: div
  bibliography_group_tag: "h5,h6"
  bibtex_filters: [htmllinks]
  details_layout: bib-detail.html
  details_link: ✒︎
  group_by: type
  repository: /assets/files
  type_order: [book, article, wiki, inproceedings, manual]
  type_names:
    article: Articles
    inproceedings: Conference Proceedings
    wiki: Wikipedia Entries
    documentary: Documentaries
  style: /assets/csl/apa.csl  