title: Essayer
description: 
baseurl: /essayer
url: https://constellationcolon.github.io
permalink: none

exclude: [archive, bin]
keep_files: [assets]

plugins_dir:
  - _essential_plugins
  - _nonessential_plugins

collections:
  all_tags: {output: true, permalink: /tags/:name}
  stacks: {output: true}
  poems: {output: true}
  zettel: {output: true, permalink: /zettelkasten/:name}

defaults:
  - scope: {path: "", type: "all_tags"}
    values: {layout: "tags"}
  - scope: {path: "", type: "stacks"}
    values: {layout: "stacks"}
  - scope: {path: "", type: "zettel"}
    values: {layout: "zettel"}
  - scope: {path: "", type: "poems"}
    values: {layout: "poem"}
  - scope: {path: "", type: "posts"}
    values: {layout: "essai"}
  - scope: {path: "", type: "drafts"}
    values: {layout: "essai"}

markdown: Kramdown

show_drafts: true
livereload: true

scholar:
  bibliography: "**/*.bib{,tex}"
  bibliography_template: bib
  bibliography_list_tag: div
  bibliography_item_tag: div
  bibliography_group_tag: "h5,h6"
  bibtex_filters: [htmllinks]
  group_by: type
  repository: /assets/files
  type_order: [book, article, wiki, inproceedings, manual]
  type_names:
    article: Articles
    inproceedings: Conference Proceedings
    documentary: Documentaries
    music: Music
    radio: Radio
    wiki: Wikipedia Entries
  style: /assets/csl/apa.csl  
