title: Essayer
description: >-
  Lorem ipsum dolor sit amet
baseurl: "/essayer"
url: "https://constellationcolon.github.io"
permalink: none
exclude: ["bin"]

collections:
  - books

github: constellationcolon
linkedin: suhang42

markdown: Kramdown

scholar:
  bibliography: "**/*.bib{,tex}"
  bibliography_template: bib
  bibtex_filters:
    - htmllinks
  details_layout: bibtex.html
  details_link: ✒︎
  group_by: type
  type_names:
    article: Articles
    inproceedings: Conference Proceedings
  relative: /essayer/stacks.html
  repository: /assets/files