title: Essayer
description: >-
  Lorem ipsum dolor sit amet
baseurl: "/essayer"
url: "https://constellationcolon.github.io"

github: constellationcolon
linkedin: suhang42

markdown: CommonMarkGhPages
commonmark:
  options: ["FOOTNOTES", "SMART"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
